In [24]:
import pandas as pd
import yaml

In [42]:
df = pd.read_csv("data/raw/weather_observation.csv")
df

,id,station_id,source_id,unit,observed_at,created_at,quality_status,raw_record_id,pipeline_version,variable,value
0,3,1,2,degC,2026-08-07 05:00:00.000000 +00:00,2026-08-07 20:30:15.707971 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,air_temperature_2m,28.000000
1,4,1,2,degC,2026-08-07 05:00:00.000000 +00:00,2026-08-07 20:30:15.707971 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,dew_point_2m,24.000000
2,5,1,2,m/s,2026-08-07 05:00:00.000000 +00:00,2026-08-07 20:30:15.707971 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,wind_speed_10m,1.543332
3,6,1,2,deg,2026-08-07 05:00:00.000000 +00:00,2026-08-07 20:30:15.707971 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,wind_direction_10m,40.000000
4,7,1,2,hPa,2026-08-07 05:00:00.000000 +00:00,2026-08-07 20:30:15.707971 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,surface_pressure,1011.000000
...,...,...,...,...,...,...,...,...,...,...,...
10983,37700,1,2,m/s,2026-10-20 23:00:00.000000 +00:00,2026-10-21 00:01:31.235658 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,wind_speed_10m,5.144440
10984,37701,1,2,deg,2026-10-20 23:00:00.000000 +00:00,2026-10-21 00:01:31.235658 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,wind_direction_10m,20.000000
10985,37702,1,2,hPa,2026-10-20 23:00:00.000000 +00:00,2026-10-21 00:01:31.235658 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,surface_pressure,1006.000000
10986,37703,1,2,m,2026-10-20 23:00:00.000000 +00:00,2026-10-21 00:01:31.235658 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,visibility,10000.000000
10987,37704,1,2,%,2026-10-20 23:00:00.000000 +00:00,2026-10-21 00:01:31.235658 +00:00,valid,source=metar/dataset=observations/location=sim...,metar-0.1.0,cloud_cover,18.750000

In [35]:
params = yaml.safe_load(open("params.yaml", encoding="utf-8"))["prepare"]
target = params["target"] 

def pget(key, default=None):
    return params.get(key, default)

In [43]:
# df.pivot(index="observed_at", values="value", columns="variable")
df = df.pivot(index=pget("index", "observed_at"), values=pget("values", "value"), columns=pget("variables", "variable"))
df

variable,air_temperature_2m,cloud_cover,dew_point_2m,surface_pressure,visibility,wind_direction_10m,wind_gust_10m,wind_speed_10m
observed_at,,,,,,,,
2026-08-06 08:00:00.000000 +00:00,28.0,NaN,24.0,1008.0,10000.0,NaN,NaN,1.028888
2026-08-06 09:00:00.000000 +00:00,27.0,NaN,25.0,1008.0,10000.0,NaN,NaN,1.028888
2026-08-06 10:00:00.000000 +00:00,28.0,NaN,25.0,1009.0,10000.0,290.0,NaN,1.543332
2026-08-06 11:00:00.000000 +00:00,26.0,18.75,24.0,1009.0,10000.0,NaN,NaN,1.028888
2026-08-06 12:00:00.000000 +00:00,27.0,18.75,24.0,1010.0,10000.0,140.0,NaN,2.057776
...,...,...,...,...,...,...,...,...
2026-10-20 19:00:00.000000 +00:00,33.0,18.75,25.0,1007.0,10000.0,310.0,NaN,2.572220
2026-10-20 20:00:00.000000 +00:00,33.0,18.75,25.0,1006.0,10000.0,330.0,NaN,2.572220
2026-10-20 21:00:00.000000 +00:00,33.0,18.75,25.0,1006.0,10000.0,330.0,NaN,3.086664
2026-10-20 22:00:00.000000 +00:00,32.0,18.75,25.0,1006.0,10000.0,20.0,NaN,4.629996
2026-10-20 23:00:00.000000 +00:00,31.0,18.75,24.0,1006.0,10000.0,20.0,NaN,5.144440

In [ ]:
df.info()